version: '3.8'

services:
  pynapple:
    build: .
    ports:
      - "5001:80"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - PYTHONPATH=/app/pynapple
    volumes:
      - ..:/app
    command: ["gunicorn", "-b", "0.0.0.0:80", "run:app"]

